# https://projecteuler.net/problem=719
from lib import initialize, conclude, msg, sum_list
from itertools import combinations
import time
import math

if __name__ == '__main__':

    try:

        result_data = initialize(719, 128088830547982, 0, 0, [])

        def deep_copy(arr):
            new_arr = []
            for x in range(0, len(arr), 1):
                new_arr.append(arr[x])
            return new_arr

        def max_num():
            return math.pow(10, 12)

        def max_len():
            return len(str(max_num()))

        # Faster to compute this way
        ## from roots rather than every number then verify if perfect root...
        def make_square_roots():
            perfect_squares = []
            roots = []
            last_square_root = 1
            while(True):
                sq_rt = last_square_root * last_square_root
                if sq_rt > max_num():
                    break

                perfect_squares.append(last_square_root * last_square_root)
                roots.append(last_square_root)
                last_square_root += 1

            return roots, perfect_squares

        '''
        Solution
        '''

        # Must generate these before to meet absolute execution time requirements.
        ## I know of no named algorithm that generates cuts ("Dedekind"-style) generalized for every n.
        ## ChatGPT generated this method and I modified it slightly.
        def find_all_splits(n):
            msg(result_data, "Cut caching generated for length: " + str(n))
            results = []

            for r in range(n):
                for cuts in combinations(range(1, n), r):
                    boundaries = (0,) + cuts + (n,)

                    inner_results = []
                    for idx in range(len(boundaries) - 1):
                        inner_results.append((boundaries[idx], boundaries[idx + 1]))
                    
                    if len(inner_results) >= 2:
                        results.append(inner_results)

            # msg(results)
            return results

        CACHE= {}
            
        def cache_splits():
            for r in range(2, max_len()+1, 1):
                CACHE[r] = find_all_splits(r)

        msg(result_data, "The following Cut Algorithm was partly generated by ChatGPT and Google AI (with some modification)...")
        cache_splits()
        msg(result_data, "Cut Algorithm caching completed...")

        def is_s_number(perfect_square_str, root):
            splits = CACHE.get(len(perfect_square_str))

            for partition in splits:
                inner_total = 0
                for i, j in partition:
                    inner_total += int(perfect_square_str[i:j])

                if inner_total == root:
                    return True

            return False

        def solve():
            ALGO_BEGIN = time.time()
            solution_result = 0

            ROOTS, SQUARES = make_square_roots() # 1000000

            for x in range(0, len(ROOTS), 1):
                root = ROOTS[x]
                perfect_square = SQUARES[x]
                perfect_square_str = str(perfect_square)
                # msg(result_data, "Trying: " + perfect_square_str)

                if len(perfect_square_str) < 2:
                    continue

                if is_s_number(perfect_square_str, root):
                    solution_result += perfect_square
                    msg(result_data, "S-number found: " + perfect_square_str + " with root: " + str(root) + " | Running total: " + str(solution_result) )

            conclude(result_data, solution_result, ALGO_BEGIN)

        solve()

    except Exception as ex:

        print('Exception: ' + str(ex))